@startuml Architecture

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Constell Architecture

Person(user, "ユーザー", "サービスを利用するユーザー")

System_Boundary(constell, "Constell") {
    Container(androidApp, "Androidアプリ", "Jetpack Compose", "ユーザーが利用するAndroidアプリ")

    Boundary(supabase, "Supabase") {
        Container(auth, "Auth", "Supabase", "認証・認可基盤")
        Container(edgeFunctions, "Edge Functions", "Deno / TypeScript", "記事内容の要約・ベクトル化を行い保存する関数")
        Container(postgrest, "PostgRESTサーバー", "PostgREST", "HTTPリクエストをSQLに変換し、DBとやりとりするサーバー")
        ContainerDb(db, "DB", "PostgreSQL, pgvector", "データの保存、RLS、記事同士の類似度を計算・保存するトリガー関数")
    }
}

System_Ext(geminiApi, "Gemini API", "記事の要約とベクトル化を行う外部API")

Rel(user, androidApp, "利用する")
Rel(androidApp, auth, "サインイン・サインアップ処理、セッション管理、パスワードリセット")
Rel(androidApp, postgrest, "1. 記事の登録", "HTTP, REST API")
Rel(postgrest, db, "2. 記事登録処理のSQLクエリ")
Rel(db, edgeFunctions, "3. 記事の登録をトリガーに処理開始", "Database Webhooks")
Rel(edgeFunctions, geminiApi, "4. 記事の要約とベクトル化", "HTTP, REST API")
Rel(edgeFunctions, postgrest, "5. 要約・ベクトル化した記事を登録", "HTTP, REST API")
Rel(postgrest, db, "6. 記事を登録するSQLクエリ")

@enduml